# Introduction to Scikit-Learn Workflow (sklearn)

Sci kit learn Demo:
0. Sci-kit Learn workflow
1. Getting the data ready
2. Choosing the right model/algorithm for the problem
3. Fitting the model to make predictions
4. Evaluating the Model
5. Improving model
6. Save and load the trained model
7. Putting it all together

#### 0. Import Libraries

In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### 1. Import Data

In [40]:
file_path = r'B:\jupyter\Projects\Cheat Sheets\Sci Kit Learn Data\heart-disease.csv'
heart_disease = pd.read_csv(file_path)
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

#### 2. Set the feature matrix and target variable to predict

In [3]:
# X : Set the features matrix 
X = heart_disease.drop("target",axis=1)

# Y : Set the label (Variable to predict)
Y = heart_disease["target"]

#### 3. Choose the right model and hyperparameters

In [4]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# Default Hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

#### 4. Fit the model to the training data

In [5]:
from sklearn.model_selection import train_test_split

#Split our data from X and Y to leave some parts for training and testing
#0.2 = 20% data will be testing while 80% willbe used for training
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.2)

In [6]:
#Find the patterns from the training data
clf.fit(X_train,y_train)

RandomForestClassifier()

In [7]:
# Make a prediction to test
# Must have the same dimension as the features/columns we have fitted to the model
y_preds = clf.predict(X_test)
y_preds

array([1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1], dtype=int64)

In [17]:
X_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
173,58,1,2,132,224,0,0,173,0,3.2,2,2,3
107,45,0,0,138,236,0,0,152,1,0.2,1,0,2
12,49,1,1,130,266,0,1,171,0,0.6,2,0,2
105,68,0,2,120,211,0,0,115,0,1.5,1,0,2
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,44,0,2,118,242,0,1,149,0,0.3,1,1,2
209,59,1,0,140,177,0,1,162,1,0.0,2,1,3
143,67,0,0,106,223,0,1,142,0,0.3,2,2,2
32,44,1,1,130,219,0,0,188,0,0.0,2,0,2
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2

In [19]:
X_test["target"] = y_preds
X_test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
173,58,1,2,132,224,0,0,173,0,3.2,2,2,3,1
107,45,0,0,138,236,0,0,152,1,0.2,1,0,2,1
12,49,1,1,130,266,0,1,171,0,0.6,2,0,2,1
105,68,0,2,120,211,0,0,115,0,1.5,1,0,2,1
25,71,0,1,160,302,0,1,162,0,0.4,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,44,0,2,118,242,0,1,149,0,0.3,1,1,2,1
209,59,1,0,140,177,0,1,162,1,0.0,2,1,3,0
143,67,0,0,106,223,0,1,142,0,0.3,2,2,2,1
32,44,1,1,130,219,0,0,188,0,0.0,2,0,2,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1

In [8]:
y_test

173    0
107    1
12     1
105    1
25     1
      ..
146    1
209    0
143    1
32     1
6      1
Name: target, Length: 61, dtype: int64

### 5. Evaluate the model

#### Accuracy Metric

In [9]:
#1.0 is 100% accurate
clf.score(X_train,y_train)

1.0

In [10]:
#85% accuracy (Model has never seen this data nor the labels)
clf.score(X_test,y_test)

0.819672131147541

#### Classification Matrix
Compares the test labels and prediction labels

In [11]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print (classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.88      0.72      0.79        29
           1       0.78      0.91      0.84        32

    accuracy                           0.82        61
   macro avg       0.83      0.82      0.82        61
weighted avg       0.83      0.82      0.82        61

In [12]:
confusion_matrix(y_test,y_preds)

array([[21,  8],
       [ 3, 29]], dtype=int64)

In [13]:
accuracy_score(y_test,y_preds)

0.819672131147541

### 6. Improve Model

In [14]:
# Try different amount of n_estimators
np.random.seed(42)
for i in range(10,100,10):
    print (f"Trying model with {i} estimators....")
    clf = RandomForestClassifier(n_estimators=i)
    clf = RandomForestClassifier(n_estimators=i).fit(X_train,y_train)
    print(f"Model accuracy on test set: {clf.score(X_test,y_test) * 100:.2f}%")
    print("")

Trying model with 10 estimators....
Model accuracy on test set: 77.05%

Trying model with 20 estimators....
Model accuracy on test set: 80.33%

Trying model with 30 estimators....
Model accuracy on test set: 80.33%

Trying model with 40 estimators....
Model accuracy on test set: 78.69%

Trying model with 50 estimators....
Model accuracy on test set: 83.61%

Trying model with 60 estimators....
Model accuracy on test set: 83.61%

Trying model with 70 estimators....
Model accuracy on test set: 80.33%

Trying model with 80 estimators....
Model accuracy on test set: 78.69%

Trying model with 90 estimators....
Model accuracy on test set: 80.33%

### 7. Save the model and load it

In [15]:
import pickle

pickle.dump(clf,open("random_forest_model_1.pkl","wb"))

In [16]:
loaded_model = pickle.load(open("random_forest_model_1.pkl","rb"))
loaded_model.score(X_test,y_test)

0.8032786885245902